### ISSUE TITLE
Story Board

### ISSUE THREAD

**Issue by suptoasty** [suptoasty/tools-site#4]
### Pages:
Home Page (default welcome message)
Courses Page (courses you need as a computer science major)
About Us Page (Info and images of CS things)

**Comment by suptoasty** [comment]
Added Bare Bones pages with navbar using bootsrap, jquery, and popper.js

**Comment by suptoasty** [comment]
### Todo:

- [ ] Add text content to each page
- [ ] Add imgs to each page
- [ ] Add carousel (using owl carousel 2) where necessary

**Comment by suptoasty** [comment]
@ryanburnett1 you should add an image and info to your profile card in the about page when you get a chance

**Comment by suptoasty** [comment]
Only home page is left. @ryanburnett1  what should it have?

**Comment by suptoasty** [comment]
![Story boards](https://user-images.githubusercontent.com/16758490/91890132-9cc84500-ec54-11ea-992e-00aa1b72eea9.png)
![Courses](https://user-images.githubusercontent.com/16758490/91890134-9e920880-ec54-11ea-93d4-a42bd3e8a6d1.png)
![Preparation](https://user-images.githubusercontent.com/16758490/91890140-9fc33580-ec54-11ea-9119-da06c5901b79.png)
